# TODO: Change to your own configs

[package]
name = "fly_axum"
version = "0.1.0"
authors = ["Gabriel Nigro <nigrorodriguesgabriel@gmail.com>"]
edition = "2021"

[dependencies]
axum = "0.7.4"
tokio = { version = "1", features = ["full"] }
